<?php
/* Built-in places: [IATA city/airport code, city, country, ISO country code]. Online search adds the rest. */
return [
    ['BKK', 'Bangkok', 'Thailand', 'TH'],
    ['HKT', 'Phuket', 'Thailand', 'TH'],
    ['CNX', 'Chiang Mai', 'Thailand', 'TH'],
    ['USM', 'Koh Samui', 'Thailand', 'TH'],
    ['DPS', 'Bali', 'Indonesia', 'ID'],
    ['CGK', 'Jakarta', 'Indonesia', 'ID'],
    ['SIN', 'Singapore', 'Singapore', 'SG'],
    ['KUL', 'Kuala Lumpur', 'Malaysia', 'MY'],
    ['SGN', 'Ho Chi Minh City', 'Vietnam', 'VN'],
    ['HAN', 'Hanoi', 'Vietnam', 'VN'],
    ['MNL', 'Manila', 'Philippines', 'PH'],
    ['HKG', 'Hong Kong', 'Hong Kong', 'HK'],
    ['TYO', 'Tokyo', 'Japan', 'JP'],
    ['OSA', 'Osaka', 'Japan', 'JP'],
    ['SEL', 'Seoul', 'South Korea', 'KR'],
    ['TPE', 'Taipei', 'Taiwan', 'TW'],
    ['PEK', 'Beijing', 'China', 'CN'],
    ['SHA', 'Shanghai', 'China', 'CN'],
    ['DEL', 'Delhi', 'India', 'IN'],
    ['BOM', 'Mumbai', 'India', 'IN'],
    ['GOI', 'Goa', 'India', 'IN'],
    ['CMB', 'Colombo', 'Sri Lanka', 'LK'],
    ['MLE', 'Malé', 'Maldives', 'MV'],
    ['KTM', 'Kathmandu', 'Nepal', 'NP'],
    ['DXB', 'Dubai', 'United Arab Emirates', 'AE'],
    ['AUH', 'Abu Dhabi', 'United Arab Emirates', 'AE'],
    ['DOH', 'Doha', 'Qatar', 'QA'],
    ['MCT', 'Muscat', 'Oman', 'OM'],
    ['AMM', 'Amman', 'Jordan', 'JO'],
    ['TLV', 'Tel Aviv', 'Israel', 'IL'],
    ['IST', 'Istanbul', 'Türkiye', 'TR'],
    ['AYT', 'Antalya', 'Türkiye', 'TR'],
    ['CAI', 'Cairo', 'Egypt', 'EG'],
    ['HRG', 'Hurghada', 'Egypt', 'EG'],
    ['RAK', 'Marrakech', 'Morocco', 'MA'],
    ['AGA', 'Agadir', 'Morocco', 'MA'],
    ['CPT', 'Cape Town', 'South Africa', 'ZA'],
    ['JNB', 'Johannesburg', 'South Africa', 'ZA'],
    ['NBO', 'Nairobi', 'Kenya', 'KE'],
    ['ZNZ', 'Zanzibar', 'Tanzania', 'TZ'],
    ['MRU', 'Mauritius', 'Mauritius', 'MU'],
    ['SEZ', 'Seychelles', 'Seychelles', 'SC'],
    ['RUN', 'Réunion', 'Réunion', 'RE'],
    ['DSS', 'Dakar', 'Senegal', 'SN'],
    ['SYD', 'Sydney', 'Australia', 'AU'],
    ['MEL', 'Melbourne', 'Australia', 'AU'],
    ['PER', 'Perth', 'Australia', 'AU'],
    ['BNE', 'Brisbane', 'Australia', 'AU'],
    ['AKL', 'Auckland', 'New Zealand', 'NZ'],
    ['NYC', 'New York', 'United States', 'US'],
    ['LAX', 'Los Angeles', 'United States', 'US'],
    ['SFO', 'San Francisco', 'United States', 'US'],
    ['MIA', 'Miami', 'United States', 'US'],
    ['LAS', 'Las Vegas', 'United States', 'US'],
    ['ORL', 'Orlando', 'United States', 'US'],
    ['CHI', 'Chicago', 'United States', 'US'],
    ['BOS', 'Boston', 'United States', 'US'],
    ['SEA', 'Seattle', 'United States', 'US'],
    ['HNL', 'Honolulu', 'United States', 'US'],
    ['YTO', 'Toronto', 'Canada', 'CA'],
    ['YVR', 'Vancouver', 'Canada', 'CA'],
    ['YMQ', 'Montreal', 'Canada', 'CA'],
    ['MEX', 'Mexico City', 'Mexico', 'MX'],
    ['CUN', 'Cancún', 'Mexico', 'MX'],
    ['HAV', 'Havana', 'Cuba', 'CU'],
    ['PUJ', 'Punta Cana', 'Dominican Republic', 'DO'],
    ['CUR', 'Curaçao', 'Curaçao', 'CW'],
    ['AUA', 'Aruba', 'Aruba', 'AW'],
    ['BON', 'Bonaire', 'Bonaire', 'BQ'],
    ['SXM', 'Sint Maarten', 'Sint Maarten', 'SX'],
    ['PBM', 'Paramaribo', 'Suriname', 'SR'],
    ['MBJ', 'Montego Bay', 'Jamaica', 'JM'],
    ['SJO', 'San José', 'Costa Rica', 'CR'],
    ['LIM', 'Lima', 'Peru', 'PE'],
    ['BOG', 'Bogotá', 'Colombia', 'CO'],
    ['CTG', 'Cartagena', 'Colombia', 'CO'],
    ['GIG', 'Rio de Janeiro', 'Brazil', 'BR'],
    ['SAO', 'São Paulo', 'Brazil', 'BR'],
    ['BUE', 'Buenos Aires', 'Argentina', 'AR'],
    ['SCL', 'Santiago', 'Chile', 'CL'],
    ['BCN', 'Barcelona', 'Spain', 'ES'],
    ['MAD', 'Madrid', 'Spain', 'ES'],
    ['AGP', 'Málaga', 'Spain', 'ES'],
    ['PMI', 'Palma de Mallorca', 'Spain', 'ES'],
    ['IBZ', 'Ibiza', 'Spain', 'ES'],
    ['TFS', 'Tenerife', 'Spain', 'ES'],
    ['LPA', 'Gran Canaria', 'Spain', 'ES'],
    ['ACE', 'Lanzarote', 'Spain', 'ES'],
    ['FUE', 'Fuerteventura', 'Spain', 'ES'],
    ['ALC', 'Alicante', 'Spain', 'ES'],
    ['VLC', 'Valencia', 'Spain', 'ES'],
    ['SVQ', 'Seville', 'Spain', 'ES'],
    ['LIS', 'Lisbon', 'Portugal', 'PT'],
    ['OPO', 'Porto', 'Portugal', 'PT'],
    ['FAO', 'Faro', 'Portugal', 'PT'],
    ['FNC', 'Madeira', 'Portugal', 'PT'],
    ['PDL', 'Azores', 'Portugal', 'PT'],
    ['NCE', 'Nice', 'France', 'FR'],
    ['PAR', 'Paris', 'France', 'FR'],
    ['ROM', 'Rome', 'Italy', 'IT'],
    ['MIL', 'Milan', 'Italy', 'IT'],
    ['NAP', 'Naples', 'Italy', 'IT'],
    ['VCE', 'Venice', 'Italy', 'IT'],
    ['CTA', 'Catania', 'Italy', 'IT'],
    ['PMO', 'Palermo', 'Italy', 'IT'],
    ['CAG', 'Cagliari', 'Italy', 'IT'],
    ['ATH', 'Athens', 'Greece', 'GR'],
    ['JTR', 'Santorini', 'Greece', 'GR'],
    ['JMK', 'Mykonos', 'Greece', 'GR'],
    ['HER', 'Crete (Heraklion)', 'Greece', 'GR'],
    ['RHO', 'Rhodes', 'Greece', 'GR'],
    ['CFU', 'Corfu', 'Greece', 'GR'],
    ['SPU', 'Split', 'Croatia', 'HR'],
    ['DBV', 'Dubrovnik', 'Croatia', 'HR'],
    ['MLA', 'Malta', 'Malta', 'MT'],
    ['LCA', 'Larnaca', 'Cyprus', 'CY'],
    ['LON', 'London', 'United Kingdom', 'GB'],
    ['EDI', 'Edinburgh', 'United Kingdom', 'GB'],
    ['DUB', 'Dublin', 'Ireland', 'IE'],
    ['REK', 'Reykjavík', 'Iceland', 'IS'],
    ['CPH', 'Copenhagen', 'Denmark', 'DK'],
    ['OSL', 'Oslo', 'Norway', 'NO'],
    ['STO', 'Stockholm', 'Sweden', 'SE'],
    ['HEL', 'Helsinki', 'Finland', 'FI'],
    ['RVN', 'Rovaniemi', 'Finland', 'FI'],
    ['PRG', 'Prague', 'Czechia', 'CZ'],
    ['BUD', 'Budapest', 'Hungary', 'HU'],
    ['VIE', 'Vienna', 'Austria', 'AT'],
    ['KRK', 'Kraków', 'Poland', 'PL'],
    ['BER', 'Berlin', 'Germany', 'DE'],
    ['MUC', 'Munich', 'Germany', 'DE'],
];
